In [ ]:
import requests

BASE_URL = "http://0.0.0.0:4008"


## reranker

In [18]:
queries = ["What is the capital of China?", "Explain gravity", "Explain gravity"]
documents = [
    "The capital of China is Beijing.",
    "The capital of China is Beijing.",
    "Gravity is a force that attracts two bodies towards each other. It gives weight to physical objects and is responsible for the movement of planets around the sun.",
]

In [19]:
response = requests.post(
    f"{BASE_URL}/reranker/api",
    json={"questions": queries, "texts": documents},
)
response.json()

[0.99853515625, 2.390146255493164e-05, 0.99853515625]

## embedding

In [24]:
queries = ["What is the capital of China?", "Explain gravity"]
documents = [
    "The capital of China is Beijing.",
    "Gravity is a force that attracts two bodies towards each other. It gives weight to physical objects and is responsible for the movement of planets around the sun.",
]


In [25]:
import numpy as np 
response = requests.post(
    f"{BASE_URL}/embedding/api",
    json={"input": queries,"is_query": True},
)
query_embeddings = response.json()

query_embeddings = np.array(query_embeddings)
query_embeddings.shape

(2, 1024)

In [26]:
response = requests.post(
    f"{BASE_URL}/embedding/api",
    json={"input": documents, "is_query": False},
)
documents_embeddings = response.json()

documents_embeddings = np.array(documents_embeddings)
documents_embeddings.shape


(2, 1024)

In [27]:
query_embeddings @ documents_embeddings.T

array([[0.76452172, 0.14139068],
       [0.13580755, 0.59995794]])

In [28]:
query_embeddings[:, :3]

array([[-5.08422852e-02, -2.91290283e-02, -3.39746475e-05],
       [-1.11236572e-02, -3.42407227e-02, -1.11198425e-03]])

In [29]:
documents_embeddings[:, :3]

array([[-0.04724121, -0.02067566,  0.00362206],
       [-0.05310059, -0.01506042, -0.00127506]])